version: "3.4"
services:
  kis_website:
    image: node:alpine
    container_name: kis-website
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
